### ISSUE TITLE
[APP REQUEST]: owncloud

### ISSUE THREAD

**Issue by jobrien2001** [Qballjos/portainer_templates#37]
### Dockerhub Link: ###
https://hub.docker.com/r/owncloud/server/

### Description ###
A nextcloud type app

### Separate Database? ###
mariadb, also redis

### Fill this out as best as you can. Documentation about these can be found here: https://www.portainer.io/documentation/how-to-use-templates/

```json
{
  "version": "2",
  "templates": [
    {
      "categories": [
        "Cloud"
      ],
      "description": "OwnCloud provides universal access to your files via the web, your computer or your mobile devices — wherever you are.",
      "env": [
        {
          "default": "localhost:8080",
          "label": "OWNCLOUD_DOMAIN",
          "name": "OWNCLOUD_DOMAIN"
        },
        {
          "default": "mysql",
          "label": "OWNCLOUD_DB_TYPE",
          "name": "OWNCLOUD_DB_TYPE"
        },
        {
          "default": "owncloud",
          "label": "OWNCLOUD_DB_NAME",
          "name": "OWNCLOUD_DB_NAME"
        },
        {
          "default": "owncloud",
          "label": "OWNCLOUD_DB_USERNAME",
          "name": "OWNCLOUD_DB_USERNAME"
        },
        {
          "default": "owncloud",
          "label": "OWNCLOUD_DB_PASSWORD",
          "name": "OWNCLOUD_DB_PASSWORD"
        },
        {
          "default": "mariadb",
          "label": "OWNCLOUD_DB_HOST",
          "name": "OWNCLOUD_DB_HOST"
        },
        {
          "default": "admin",
          "label": "ADMIN_USERNAME",
          "name": "ADMIN_USERNAME"
        },
        {
          "default": "password",
          "label": "ADMIN_PASSWORD",
          "name": "ADMIN_PASSWORD"
        },
        {
          "default": "true",
          "label": "OWNCLOUD_MYSQL_UTF8MB4",
          "name": "OWNCLOUD_MYSQL_UTF8MB4"
        },
        {
          "default": "true",
          "label": "OWNCLOUD_REDIS_ENABLED",
          "name": "OWNCLOUD_REDIS_ENABLED"
        },
        {
          "default": "redis",
          "label": "OWNCLOUD_REDIS_HOST",
          "name": "OWNCLOUD_REDIS_HOST"
        },
        {
          "default": "8080",
          "label": "HTTP_PORT",
          "name": "HTTP_PORT"
        }
      ],
      "image": "owncloud/server",
      "logo": "https://d1q6f0aelx0por.cloudfront.net/product-logos/24f2a51f-4b42-4dea-98c5-6bb9603c1b4e-owncloud.png",
      "name": "owncloud",
      "platform": "linux",
      "ports": [
        "8080:8080/tcp"
      ],
      "restart_policy": "unless-stopped",
      "title": "owncloud",
      "type": 1,
      "volumes": [
        {
          "bind": "/portainer/Files/AppData/Config/apps",
          "container": "/mnt/data"
        }
      ]
    }
```

Here is a copy of the official compose:

```
version: "3"

volumes:
  files:
    driver: local
  mysql:
    driver: local
  redis:
    driver: local

services:
  owncloud:
    image: owncloud/server:${OWNCLOUD_VERSION}
    container_name: owncloud_server
    restart: always
    ports:
      - ${HTTP_PORT}:8080
    depends_on:
      - mariadb
      - redis
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=mariadb
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - files:/mnt/data

  mariadb:
    image: mariadb:10.5
    container_name: owncloud_mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=owncloud
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=owncloud"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql:/var/lib/mysql

  redis:
    image: redis:6
    container_name: owncloud_redis
    restart: always
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis:/data
```
